openapi: 3.0.0
info:
  version: 1.0.0
  title: Human Resource Development Application
  description: |
    # By Alyuza Satrio Prayogo

    ## Flowchart
    ---
    ![Swagger logo](https://i.ibb.co/CnnFqY5/main-Flowchart.png)

    ```
    Available Account
    "username" : "hrd.admin",
    "password" : "admin1234",
    "role" : "admin"
    ```
    Example pada bagian Login sudah berisikan username & password Admin untuk memudahkan pengisian data.

    ---

servers:
  - url: https://erin-beautiful-peacock.cyclic.app
    description: 'Production server'
  - url: http://localhost:3000
    description: 'Development server'

components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Bearer with JWT Token'

paths:
  /v1/auth/login:
    post:
      tags:
        - Home
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: hrd.admin
                password:
                  type: string
                  example: admin1234
      responses:
        '200':
          description: Success

  /v1/user/viewProfile/{userId}:
    get:
      tags:
       - Employee
      security:
        - bearer_auth: []
      summary: View own profile
      responses:
        '200':
          description: Success

  /v1/user/changePassword/{userId}:
    patch:
      tags:
       - Employee
      security:
        - bearer_auth: []
      summary: Change password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: newpassword1234
                repeatPassword:
                  type: string
                  example: newpassword1234
      responses:
        '200':
          description: Success

  /v1/admin/register:
    post:
      tags:
       - Administrator
      security:
        - bearer_auth: []
      summary: Add employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                  example: Alyuza Satrio Prayogo
                jobPosition:
                  type: string
                  example: Junior Software Engineer
                department:
                  type: string
                  example: Tech
                salary:
                  type: number
                  example: 8500000
                username:
                  type: string
                  example: alyuza
                password:
                  type: string
                  example: user1234
                repeatPassword:
                  type: string
                  example: user1234
                role:
                  type: string
                  example: user
      responses:
        '200':
          description: Success

  /v1/admin/getAllUsers:
    get:
      tags:
       - Administrator
      security:
        - bearer_auth: []
      summary: Get all employee data
      responses:
        '200':
          description: Success

  /v1/admin/getUser/{userId}:
    get:
      tags:
       - Administrator
      security:
        - bearer_auth: []
      summary: Get data by id
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          example: 64edd0945e36f401709dd77e
      responses:
        '200':
          description: Success

  /v1/admin/update/{userId}:
    put:
      tags:
       - Administrator
      security:
        - bearer_auth: []
      summary: Update job and/or salary
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          example: 64edd0945e36f401709dd77e
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                salary:
                  type: number
                  example: 24000000
                jobPosition:
                  type: string
                  example: Manager
      responses:
        '200':
          description: Success
          
  /v1/admin/delete/{userId}:
    delete:
      tags:
       - Administrator
      security:
        - bearer_auth: []
      summary: Soft delete employee
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          example: 64edd0945e36f401709dd77e
      responses:
        '200':
          description: Success

